name: Airflow CI Pipeline

on:
  push:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev
  pull_request:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev

jobs:
  build:
    container:
      image: apache/airflow:2.10.2-python3.9

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies for airflow project
        run: |
          cd airflow
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd airflow
          pytest tests/dags
