name: CI Pipeline

on:
  push:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev
  pull_request:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container: apache/airflow:2.10.2-python3.9
    volumes:
      - airflow/dags:/opt/airflow/dags
      - airflow/config:/opt/airflow/config
      - airflow/include:/opt/airflow/include
      - airflow/tests:/opt/airflow/tests
      - airflow/requirements.txt:/opt/airflow/requirements.txt

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies for airflow project
        run: |
          cd /opt/airflow
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd /opt/airflow
          pytest tests/dags
