name: CI Pipeline

on:
  push:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev
  pull_request:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: apache/airflow:2.10.2-python3.9
      volumes:
        - ${{ github.workspace }}/airflow/config:/opt/airflow/config
        - ${{ github.workspace }}/airflow/dags:/opt/airflow/dags
        - ${{ github.workspace }}/airflow/tests:/opt/airflow/tests
        - ${{ github.workspace }}/airflow/include:/opt/airflow/include
        - ${{ github.workspace }}/airflow/requirements.txt:/opt/airflow/requirements.txt

    steps:
      - name: Fix permissions for the GitHub workspace
        run: |
          chown -R $(whoami) /__w/_temp/

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies for airflow project
        run: |
          cd /opt/airflow
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd /opt/airflow
          pytest tests/dags
