name: CI Pipeline

on:
  push:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev
  pull_request:
    paths:
      - 'airflow/**'
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: apache/airflow:2.10.2-python3.9
      volumes:
        - ${{ github.workspace }}/airflow/config:/opt/airflow/config
        - ${{ github.workspace }}/airflow/dags:/opt/airflow/dags
        - ${{ github.workspace }}/airflow/tests:/opt/airflow/tests
        - ${{ github.workspace }}/airflow/include:/opt/airflow/include

    steps:
      - name: Check requirements file
        run: cat /opt/airflow/tests/requirements.txt

      - name: Copy requirements.txt
        run: cp $GITHUB_WORKSPACE/airflow/requirements.txt /opt/airflow/requirements.txt

      - name: Install dependencies for airflow project
        run: |
          cd /opt/airflow/tests
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          cd /opt/airflow
          pytest tests/dags
